#!/bin/sh
# Regression: get_extra_sources_for_bin reads the aether.toml line by
# line with a fixed-size buffer. The previous 1 KiB buffer silently
# truncated a long `extra_sources = [...]` line, dropping shims from
# the link command without any warning — link then failed with
# "undefined reference to ..." for every truncated entry.
#
# This test builds a project with ~30 extra_sources, where each path
# is 40+ chars. The one-line TOML array is ~1300+ chars — comfortably
# past 1024 but inside the new 8 KiB buffer. Every shim contributes a
# symbol; if any one gets dropped, the link fails.
#
# Shape of the repro:
#   - aether.toml with [[bin]] listing 30 extra_sources
#   - 30 shim_NN.c files, each defining int shim_NN_value(void) { return NN; }
#   - probe.ae that calls every shim_NN_value() and sums the returns.
#
# The test constructs the project in a tmpdir, so nothing persistent
# lands in tests/. Build from the tmpdir; run the resulting binary.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
AE="$ROOT/build/ae"

case "$(uname -s 2>/dev/null)" in
    MINGW*|MSYS*|CYGWIN*|Windows_NT)
        echo "  [SKIP] test_long_line on Windows"; exit 0 ;;
esac

TMPDIR="$(mktemp -d)"; trap 'rm -rf "$TMPDIR"' EXIT
PROJ="$TMPDIR/proj"
mkdir -p "$PROJ"

# Generate 30 shim files. Each filename is padded to force the
# extra_sources line past 1 KiB even if Aether normalises paths.
# shim_00_padded_filename_for_line_length.c through shim_29_…
build_shim() {
    n=$1
    v=$2   # numeric without leading zero, keeps it out of C's octal parse
    cat >"$PROJ/shim_${n}_padded_filename_for_line_length.c" <<EOF
int shim_${n}_value(void) { return ${v}; }
EOF
}

i=0
while [ "$i" -lt 30 ]; do
    if [ "$i" -lt 10 ]; then
        build_shim "0$i" "$i"
    else
        build_shim "$i" "$i"
    fi
    i=$((i + 1))
done

# Build the extra_sources array — one long line.
SRCS=""
i=0
while [ "$i" -lt 30 ]; do
    if [ "$i" -lt 10 ]; then
        name="shim_0${i}_padded_filename_for_line_length.c"
    else
        name="shim_${i}_padded_filename_for_line_length.c"
    fi
    if [ -z "$SRCS" ]; then
        SRCS="\"$name\""
    else
        SRCS="$SRCS, \"$name\""
    fi
    i=$((i + 1))
done

cat >"$PROJ/aether.toml" <<EOF
[[bin]]
name = "probe"
path = "probe.ae"
extra_sources = [$SRCS]
EOF

# Sanity: confirm the line length is past 1 KiB.
line_len=$(grep '^extra_sources' "$PROJ/aether.toml" | wc -c)
if [ "$line_len" -lt 1200 ]; then
    echo "  [FAIL] test setup: extra_sources line is $line_len bytes (expected > 1200)"
    exit 1
fi

# Build the probe — sum of 0..29 via 30 extern calls.
externs=""
calls="sum = 0"
i=0
while [ "$i" -lt 30 ]; do
    if [ "$i" -lt 10 ]; then
        nn="0${i}"
    else
        nn="${i}"
    fi
    externs="${externs}
extern shim_${nn}_value() -> int"
    calls="${calls}
    sum = sum + shim_${nn}_value()"
    i=$((i + 1))
done

cat >"$PROJ/probe.ae" <<EOF
// Auto-generated by test_long_line.sh
${externs}

main() {
${calls}
    if sum != 435 {
        print("FAIL: sum = ")
        println(sum)
        exit(1)
    }
    print("OK: 30 shims linked, sum = 435\n")
}
EOF

cd "$PROJ"
if ! "$AE" build probe.ae -o "$TMPDIR/probe" >"$TMPDIR/build.log" 2>&1; then
    echo "  [FAIL] toml_extra_sources_long_line: build failed (link should succeed after buffer-size fix)"
    sed 's/^/    /' "$TMPDIR/build.log" | tail -15
    exit 1
fi

if ! "$TMPDIR/probe" >"$TMPDIR/run.log" 2>&1; then
    echo "  [FAIL] toml_extra_sources_long_line: probe exited non-zero"
    sed 's/^/    /' "$TMPDIR/run.log" | head -5
    exit 1
fi

if ! grep -q "OK: 30 shims linked" "$TMPDIR/run.log"; then
    echo "  [FAIL] toml_extra_sources_long_line: probe didn't print success"
    sed 's/^/    /' "$TMPDIR/run.log" | head -5
    exit 1
fi

echo "  [PASS] toml_extra_sources_long_line: 30 extra_sources on a ~${line_len}-byte line linked and ran"
