#!/bin/sh
# Regression: the TOML parser's fgets buffer and the assembly-side
# buffer that splices `extra_sources` into the gcc command line are
# *two separate buffers*. A previous fix bumped the parser's
# `char line[8192]` (v0.85 changelog) but left the assembly side's
# `char toml_extra[2048]` at 2 KiB, which silently truncated
# filenames mid-string when a downstream project (subversion port)
# grew its svnserver [[bin]] extra_sources past ~2 KiB — ld got
# `cannot find ae/svnserver/handler_copy_generat: No such file or
# directory`.
#
# Shape: same as test_long_line.sh but with ~60 shims instead of 30,
# pushing the TOML line past 2.4 KiB. With the old 2 KiB toml_extra
# the link fails ("cannot find shim_...trunc..."); with the 8 KiB
# buffer we now ship, all 60 shims link and the probe returns the
# correct sum.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
AE="$ROOT/build/ae"

case "$(uname -s 2>/dev/null)" in
    MINGW*|MSYS*|CYGWIN*|Windows_NT)
        echo "  [SKIP] test_assembly_buf on Windows"; exit 0 ;;
esac

TMPDIR="$(mktemp -d)"; trap 'rm -rf "$TMPDIR"' EXIT
PROJ="$TMPDIR/proj"
mkdir -p "$PROJ"

build_shim() {
    n=$1
    v=$2
    cat >"$PROJ/shim_${n}_padded_filename_for_line_length.c" <<EOF
int shim_${n}_value(void) { return ${v}; }
EOF
}

N=60

i=0
while [ "$i" -lt "$N" ]; do
    if [ "$i" -lt 10 ]; then
        build_shim "0$i" "$i"
    else
        build_shim "$i" "$i"
    fi
    i=$((i + 1))
done

SRCS=""
i=0
while [ "$i" -lt "$N" ]; do
    if [ "$i" -lt 10 ]; then
        name="shim_0${i}_padded_filename_for_line_length.c"
    else
        name="shim_${i}_padded_filename_for_line_length.c"
    fi
    if [ -z "$SRCS" ]; then
        SRCS="\"$name\""
    else
        SRCS="$SRCS, \"$name\""
    fi
    i=$((i + 1))
done

cat >"$PROJ/aether.toml" <<EOF
[[bin]]
name = "probe"
path = "probe.ae"
extra_sources = [$SRCS]
EOF

# Sanity: confirm the line is past 2 KiB. Old assembly buffer would
# truncate here.
line_len=$(grep '^extra_sources' "$PROJ/aether.toml" | wc -c)
if [ "$line_len" -lt 2400 ]; then
    echo "  [FAIL] test setup: extra_sources line is $line_len bytes (expected > 2400)"
    exit 1
fi

# Expected sum: 0+1+...+(N-1) = N*(N-1)/2. For N=60 that's 1770.
expected=$((N * (N - 1) / 2))

externs=""
calls="sum = 0"
i=0
while [ "$i" -lt "$N" ]; do
    if [ "$i" -lt 10 ]; then
        nn="0${i}"
    else
        nn="${i}"
    fi
    externs="${externs}
extern shim_${nn}_value() -> int"
    calls="${calls}
    sum = sum + shim_${nn}_value()"
    i=$((i + 1))
done

cat >"$PROJ/probe.ae" <<EOF
// Auto-generated by test_assembly_buf.sh
${externs}

main() {
${calls}
    if sum != ${expected} {
        print("FAIL: sum = ")
        println(sum)
        exit(1)
    }
    print("OK: ${N} shims linked, sum = ${expected}\n")
}
EOF

cd "$PROJ"
if ! "$AE" build probe.ae -o "$TMPDIR/probe" >"$TMPDIR/build.log" 2>&1; then
    echo "  [FAIL] toml_extra_sources_assembly_buf: build failed"
    echo "         extra_sources line was $line_len bytes — if this ld error"
    echo "         names a truncated path, the assembly-side buffer regressed."
    sed 's/^/    /' "$TMPDIR/build.log" | tail -15
    exit 1
fi

if ! "$TMPDIR/probe" >"$TMPDIR/run.log" 2>&1; then
    echo "  [FAIL] toml_extra_sources_assembly_buf: probe exited non-zero"
    sed 's/^/    /' "$TMPDIR/run.log" | head -5
    exit 1
fi

if ! grep -q "OK: ${N} shims linked" "$TMPDIR/run.log"; then
    echo "  [FAIL] toml_extra_sources_assembly_buf: probe didn't print success"
    sed 's/^/    /' "$TMPDIR/run.log" | head -5
    exit 1
fi

echo "  [PASS] toml_extra_sources_assembly_buf: ${N} extra_sources on a ~${line_len}-byte line linked and ran"
