#!/bin/sh
# Regression: `extra_sources` now accepts multi-line TOML arrays.
# Before: the parser only handled single-line `extra_sources = [...]`,
# and projects with many shims would squash everything onto one
# ever-growing line, eventually hitting the assembly-side buffer
# limit (cf. test_assembly_buf.sh).
#
# Now:
#
#     extra_sources = [
#         "a.c",
#         "b.c",
#         "c.c"
#     ]
#
# parses the same way as
#
#     extra_sources = ["a.c", "b.c", "c.c"]
#
# so projects can format for readability without losing any entries.
#
# The probe builds 12 shims listed across 12 separate continuation
# lines, and asserts every shim links and runs. A bug in the
# multi-line handling would drop entries and produce "undefined
# reference to shim_NN_value" at link time.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
AE="$ROOT/build/ae"

case "$(uname -s 2>/dev/null)" in
    MINGW*|MSYS*|CYGWIN*|Windows_NT)
        echo "  [SKIP] test_multiline on Windows"; exit 0 ;;
esac

TMPDIR="$(mktemp -d)"; trap 'rm -rf "$TMPDIR"' EXIT
PROJ="$TMPDIR/proj"
mkdir -p "$PROJ"

build_shim() {
    n=$1
    v=$2
    cat >"$PROJ/shim_${n}.c" <<EOF
int shim_${n}_value(void) { return ${v}; }
EOF
}

N=12

i=0
while [ "$i" -lt "$N" ]; do
    if [ "$i" -lt 10 ]; then
        build_shim "0$i" "$i"
    else
        build_shim "$i" "$i"
    fi
    i=$((i + 1))
done

# Build aether.toml with each shim on its own continuation line.
{
    printf '[[bin]]\n'
    printf 'name = "probe"\n'
    printf 'path = "probe.ae"\n'
    printf 'extra_sources = [\n'
    i=0
    while [ "$i" -lt "$N" ]; do
        if [ "$i" -lt 10 ]; then
            name="shim_0${i}.c"
        else
            name="shim_${i}.c"
        fi
        if [ "$i" -eq $((N - 1)) ]; then
            printf '    "%s"\n' "$name"
        else
            printf '    "%s",\n' "$name"
        fi
        i=$((i + 1))
    done
    printf ']\n'
} >"$PROJ/aether.toml"

# Sanity: confirm we really wrote a multi-line array (not one line).
n_lines=$(wc -l <"$PROJ/aether.toml")
if [ "$n_lines" -lt 15 ]; then
    echo "  [FAIL] test setup: aether.toml is $n_lines lines (expected ~17)"
    cat "$PROJ/aether.toml"
    exit 1
fi

expected=$((N * (N - 1) / 2))

externs=""
calls="sum = 0"
i=0
while [ "$i" -lt "$N" ]; do
    if [ "$i" -lt 10 ]; then
        nn="0${i}"
    else
        nn="${i}"
    fi
    externs="${externs}
extern shim_${nn}_value() -> int"
    calls="${calls}
    sum = sum + shim_${nn}_value()"
    i=$((i + 1))
done

cat >"$PROJ/probe.ae" <<EOF
// Auto-generated by test_multiline.sh
${externs}

main() {
${calls}
    if sum != ${expected} {
        print("FAIL: sum = ")
        println(sum)
        exit(1)
    }
    print("OK: ${N} shims linked from multi-line TOML, sum = ${expected}\n")
}
EOF

cd "$PROJ"
if ! "$AE" build probe.ae -o "$TMPDIR/probe" >"$TMPDIR/build.log" 2>&1; then
    echo "  [FAIL] toml_extra_sources_multiline: build failed"
    echo "         if the ld error names a specific shim_NN_value that's"
    echo "         missing, the multi-line parser dropped it."
    sed 's/^/    /' "$TMPDIR/build.log" | tail -15
    exit 1
fi

if ! "$TMPDIR/probe" >"$TMPDIR/run.log" 2>&1; then
    echo "  [FAIL] toml_extra_sources_multiline: probe exited non-zero"
    sed 's/^/    /' "$TMPDIR/run.log" | head -5
    exit 1
fi

if ! grep -q "OK: ${N} shims linked from multi-line TOML" "$TMPDIR/run.log"; then
    echo "  [FAIL] toml_extra_sources_multiline: probe didn't print success"
    sed 's/^/    /' "$TMPDIR/run.log" | head -5
    exit 1
fi

echo "  [PASS] toml_extra_sources_multiline: ${N} shims across ${n_lines} TOML lines linked and ran"
